version: "3.9"

services:
  mysql:
    build:
      dockerfile: ./Dockerfile.mysql
      context: .
    ports:
      - '3306:3306'
    expose:
      - '3306'
  # mongodb:
  #   build:
  #     dockerfile: ./Dockerfile.mongodb
  #     context: .
  # pipeline:
  #   build:
  #     dockerfile: ./Dockerfile.pipeline